name: build & publish to docker Image
on:
    release: 
        types: [published]

jobs:
    push-to-dockerhub:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3   #Access to docker file-checkout
            - name: Login to Dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
            - name: Extract Metadata       #Extract metadata-tags n labels from our Git events-publish to dockerhub
              id: metadata                      #need to use o/p of the action
              uses: docker/metadata-action@v4
              with:
                images: mdsyedali/simple-node-api
                tags: |
                    type=semver,pattern={{version}}
                    type=semver,pattern={{major}}.{{minor}}
            - name: Build & Publish Docker Image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: /c/Users/md.a.ali/Documents/GIT/nodejs/node-js-api
                push: true
                tags: ${{ steps.metadata.outputs.tags }}
                labels: ${{ steps.metadata.outputs.labels }}






            


                                                                   



            



