name: Test Api
on: [push, workflow_dispatch]

jobs:
    test-api:
        runs-on: ubuntu-latest
        services:           #services are containers running in out host machine-nothing to do with steps 
            app:
                image: alialaa17/simple-node-api
                ports:
                    - 3001:3000
                env:
                    MONGO_HOSTNAME: mongo
            mongo: 
                image: mongo
                ports:
                    - 27017:27017

        #steps going to run directly on runner machine & can communicate with our service container 
        steps:
            - name: Dump Services context
              run: echo '${{ toJson(job.services) }}'
            - name: post a new user  #communicate from runner to service,use localhost as a host,expose a port
              run: 'curl -X POST http://localhost:3001/api/users -H ''Content-Type: application/json'' -d ''{"username": "hello","address": "dwded"}'''
            - name: Get Users
              run: curl http://localhost:3001/api/users

                    